from datetime import datetime
from pydantic import BaseModel


class CreativeConcept(BaseModel):
    """
    A single ad creative concept for paid social: hook, angle, script, shot list, and CTA.
    Generated by the agent and used as input to evaluation. Structured for later UI integration.
    """

    creative_id: str
    sku_id: str
    channel: str
    hook: str
    angle: str
    script: str
    shot_list: str
    cta: str


class PastCreative(CreativeConcept):
    """
    A creative that has already run, with performance metrics (CTR, CVR, CPA).
    Returned by search_past_creatives to give the agent examples of what worked or failed.
    """

    ctr: float
    cvr: float
    cpa: float


class ScoredConcept(BaseModel):
    """
    A concept plus its evaluation scores: deterministic heuristic and LLM critic.
    Used to rank concepts and select the top few for improved variants.
    """

    concept: CreativeConcept
    heuristic_score: float
    llm_critic_score: float


class RunArtifact(BaseModel):
    """
    A persisted output from an agent run (e.g. generated concepts, evaluation results).
    Stored via the log_artifact tool to SQLite/JSONL for later inspection and UI.
    """

    run_id: str
    artifact_type: str
    payload: dict


class MemoryEntry(BaseModel):
    """
    A stored learning keyed by brand and SKU: winning patterns, banned phrases,
    or constraints. Written by write_memory and retrieved by retrieve_memory
    so the agent improves over repeated runs.
    """

    brand_id: str
    sku_id: str
    key: str
    value: str
    created_at: datetime | None = None

# for API requests
class GenerateRequest(BaseModel):
    brand_id: str
    sku_id: str
    channel: str


class GenerateResponse(BaseModel):
    run_id: str
    concepts: list[CreativeConcept]


class RunResponse(BaseModel):
    run_id: str
    artifacts: list[dict]
